### ISSUE TITLE
Not enough Arguments Error

### ISSUE THREAD

**Issue by tbadaczewski** [cgiffard/Captionator#16]
In my implementation as well as the demo I get "Not enough arguments" errors and for the demo a syntax error in the .srt file. 

Error: uncaught exception: [Exception... "Not enough arguments"  nsresult: "0x80570001 (NS_ERROR_XPC_NOT_ENOUGH_ARGS)"  location: "JS frame :: file:///index.html :: <TOP_LEVEL> :: line 19"  data: no]

Error: uncaught exception: [Exception... "Not enough arguments"  nsresult: "0x80570001 (NS_ERROR_XPC_NOT_ENOUGH_ARGS)"  location: "JS frame :: file:///captionator.js :: <TOP_LEVEL> :: line 804"  data: no]

Error: syntax error
Source File: file:///video/arduino-en.srt
Line: 1, Column: 1
Source Code:
1

**Comment by tbadaczewski** [comment]
The arguments errors are because you guys are missing the "false" parameter on your play and pause event listeners. The other problems I had all where because my server didn't have the mime types mp4 ,webm, ogg or vtt registered.

Adding the false parameter to each function and adding the mime types solved my problem.

**Comment by cgiffard** [comment]
Thanks for finding that one - it slipped past me. :)

I'll commit a fix shortly.
