### ISSUE TITLE
track src must be local

### ISSUE THREAD

**Issue by wjarek-zz** [cgiffard/Captionator#17]
This is a bit of a corner case but I'll file it for tracking. 
I've uploaded srt file to Google Storage (http://code.google.com/apis/storage/) and tried to use it with Captionator. 
track src="http://commondatastorage.googleapis.com/jarek-test-video/test-google-io-video.srt" type="text/srt" kind="captions" srclang="zh-CN"
Captionator was not able to fetch the srt, using the file local to my embed worked.

**Comment by cgiffard** [comment]
Thanks - I'll look into ensuring 300 series responses are handled correctly. Just so I've got all the facts, what browsers could you reproduce this in?

**Comment by wjarek-zz** [comment]
Hi, I was using Chrome but turns out it was not a 3XX issue, but rather fetching the srt from a remote site. X-domain request issue ?
