### ISSUE TITLE
Subtitle text cut off

### ISSUE THREAD

**Issue by shelleyp** [cgiffard/Captionator#18]
I'm using Captionator with a copy of the Blender project's Sintel. I've tried variations of SRT and VTT, but Captionator cuts off part of the text with longer text strings. Is this a measure of video control size?

(In addition, is there a way to modify the CSS?)

**Comment by cgiffard** [comment]
I'm aware of this issue - looking into fixing it now. :)

**Comment by cgiffard** [comment]
This will most likely be corrected when I implement the new WebVTT renderer (coming very soon, because I've got real competition in this space now, haha!)

Do you think you could send me a copy of the problematic SRT/VTT file? I'd like to develop a bit of a test case to work against.

**Comment by shelleyp** [comment]
It's the SRT file for the Blender movie Sintel. The file is available at http://www.sintel.org/wp-content/content/subtitles/sintel_en.srt. I also converted it into WebVTT, but can't figure out how to attach a file to this comment.

**Comment by cgiffard** [comment]
Yeah, sorry - I don't think Github can do that yet. I'm sure it's on the books though :)

Thanks - I'll give it a quick test.

**Comment by cgiffard** [comment]
The sizing algorithm seems to overcompensate for short subtitles. I'll commit a temporary fix before the final WebVTT renderer lands.

**Comment by shelleyp** [comment]
Sounds good. Yeah, there are other tools, but I believe you're the only caption/subtitle API, so people can use their own controls and your API for captions. That's gold.

If you want other test cases for working with foreign language and vertical test, Leanback has a demo page with WebVTT subtitles available in Chinese, Arabic, and Japanese, at http://leanbackplayer.com/test/webvtt.html. The movie is another Blender movie, Elephants Dream, which you can access at http://www.elephantsdream.org.

**Comment by cgiffard** [comment]
I'm a competitive guy - Captionator'll have everything useful that leanback has very soon. ;)

Thanks for the links!

**Comment by shelleyp** [comment]
And just when you thought it was safe to use WebVTT...http://blog.gingertech.net/2011/06/27/recent-developments-around-webvtt/.

**Comment by cgiffard** [comment]
My parser is very forgiving (and I'm attempting to make it much more so.) None of the additions to the WebVTT spec should really pose much of a challenge to implement - and they all seem pretty backwards compatible anyway.

**Comment by shelleyp** [comment]
I would hope so. Even the WEBVTT FILE supposedly will still work. Changes like this are the ones that irritate me -- they introduce incompatibilities, and for no good reason.

The others seem to be additions to the functionality, not modifications.  Knock on wood.

**Comment by cgiffard** [comment]
I've pushed an update which uses the same parser code for WebVTT, SRT, SUB, and SBV (and actually should work even with bizarre mashups between them!) It does this by being very forgiving, and evaluating each timestamp and cue format on a case by case basis. Point being, I don't expect WebVTT changes to pose _that_ much of a problem for parsing.

**Comment by cgiffard** [comment]
I've rebuild the styling & caption sizing algorithm - and tested a variety of sizes of video with the sintel subs (among others) and now believe I've fixed the problem! :)

Please don't hesitate to let me know if you find anything else.
