### ISSUE TITLE
DOMException 12: SYNTAX_ERR: You must use a valid kind when creating a TimedTextTrack

### ISSUE THREAD

**Issue by codeuniquely** [cgiffard/Captionator#33]
When using Firefox 21 this exception above is thrown for this simple HTML shown below. The Subtitles show for Chrome but do not show in Firefox

```
<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
    <video controls width="640" height="480" >
         <source src="video.mp4" type="video/mp4">
        <source src="video.webm" type="video/webm">
        <source src="video.ogv" type="video/ogg">    
        <track src="video.vtt" kind="subtitle" srclang="en" label="English" />
    </video>
<script type="text/javascript" src="captionator.js"></script>
<script type="text/javascript" >
window.addEventListener("load", function(e) 
{
    captionator.captionify();
});
</script>    
</body>
```

</html>```

**Comment by joshuadwire** [comment]
I think that is because "subtitle" is not a valid text track kind. Chrome just happens to accept it anyway assuming you mean "subtitles". Firefox doesn't support text tracks, so Captionator takes over and it knows that "subtitle" isn't a valid kind.

**Comment by codeuniquely** [comment]
HI,

Sorry about that I spotted it as I posted and thus closed the issue – you can delete this one if you want..

Regards,

Steve
