### ISSUE TITLE
Which files need to be hosted

### ISSUE THREAD

**Issue by LeaYeh** [cgiffard/Captionator#48]
hi @cgiffard 
we are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host your project on cdnjs.
But I don't know which files in this repo need to be added, could you help up find out the main files? :)

**Comment by cgiffard** [comment]
Hi — just /js/captionator-min.js for the minified version, and /js/captionator.js for the unminified version. Everything else is used in build, or is an example.

Let me know how you go. :)

**Comment by PeterDaveHello** [comment]
Hi @cgiffard , what about the `css/captions.css`?

**Comment by cgiffard** [comment]
Nope, it's all built into the one file.
