### ISSUE TITLE
The git tag for the latest version

### ISSUE THREAD

**Issue by pvnr0082t** [cgiffard/Captionator#50]
Hi @cgiffard ,
The version of the latest version is v0.6. Could you please add git tag for the latest version?
Thank you.

**Comment by cgiffard** [comment]
Hi @pvnr0082t — 0.6 is unreleased. 0.5 is the latest version.

Thanks!

**Comment by cgiffard** [comment]
My apologies — you're right (gosh!) 0.6 is the latest version.

**Comment by cgiffard** [comment]
That's done now. https://github.com/cgiffard/Captionator/releases/tag/0.6
